version: '3.6'

services:
  produs:
    build: .
    container_name: 'produs'
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: postgres://postgres@db
    image: produs:latest
    ports:
      - published: 3000
        target: 3000
    depends_on:
      - db
  db:
    image: postgres:10.3-alpine
